# Python code to implement a Modbus TCP client with TLS tunneling,
# sending PV data generated by pvlib at each time step.

# Installation required (run in your environment):
# pip install pymodbus pvlib pandas

import time
import pandas as pd
import ssl
import pvlib
from pvlib import location, modelchain, pvsystem
from pvlib.temperature import TEMPERATURE_MODEL_PARAMETERS
from pymodbus.client import ModbusTlsClient
from pymodbus.exceptions import ModbusException
import pyModbusTCP.client
from pyModbusTCP.client import ModbusClient


# Step 1: Set up pvlib for generating PV data
# Using a simple fixed-mount PV system simulation with clearsky data

# Location: Example - San Francisco, CA
lat, lon, tz = 37.7749, -122.4194, 'America/Los_Angeles'
site_location = location.Location(lat, lon, tz=tz)

# Module and inverter parameters (from SAM database)

cec_modules = pvlib.pvsystem.retrieve_sam("cecmod")
sapm_inverters = pvlib.pvsystem.retrieve_sam("cecinverter")
module = cec_modules["Znshine_PV_Tech_ZXP6_72_295_P"]
inverter = sapm_inverters["ABB__MICRO_0_3_I_OUTD_US_208__208V_"]

# Temperature model parameters

temp_model_params = pvlib.temperature.TEMPERATURE_MODEL_PARAMETERS[
    "sapm"
]["open_rack_glass_glass"]

# PV System setup
system = pvsystem.PVSystem(
    module_parameters=module,
    inverter_parameters=inverter,
    temperature_model_parameters=temp_model_params,
    surface_tilt=lat,  # Optimal tilt approx latitude
    surface_azimuth=180  # South-facing
)

# ModelChain for simulation
mc = modelchain.ModelChain(
    system,
    site_location,
    aoi_model='no_loss',
    spectral_model='no_loss'
)

# Function to generate PV data for a given timestamp
def generate_pv_data(timestamp):
    times = pd.DatetimeIndex([timestamp], tz=tz)
    clearsky = site_location.get_clearsky(times)
    solar_position = site_location.get_solarposition(times)
    mc.run_model(clearsky)
    dc_power = mc.results.dc['p_mp'].values[0]  # DC power output in Watts
    return dc_power

# Step 2: Set up Modbus TLS client
# Assuming a Modbus server at localhost:802 with TLS
# For testing, disable certificate verification (NOT for production!)
sslctx = ssl.create_default_context()
sslctx.check_hostname = False
sslctx.verify_mode = ssl.CERT_NONE

client = ModbusTlsClient(
    '127.0.0.1',  # Replace with your server's hostname or IP
    port=802,     # Standard Modbus TLS port
    sslctx=sslctx
)

#client = ModbusClient(host="localhost", port=502, unit_id=1, auto_open=True)

#client = ModbusClient(host="127.0.0.1", port=8000, auto_open=True, auto_close=True)

# Connect to the server
if not client.connect():
    raise ConnectionError("Failed to connect to Modbus server")

print("Connected to Modbus TLS server")

# Step 3: Main loop - Send PV data at each time step (e.g., every 60 seconds)
try:
    while True:
        # Get current timestamp
        now = pd.Timestamp.now(tz=tz)
        
        # Generate PV data
        pv_power = generate_pv_data(now)
        print(f"{now}: Generated PV power = {pv_power:.2f} W")
        
        # Send via Modbus - Write to holding register (address 0, value as int)
        # Scale if needed (e.g., multiply by 10 for decimal precision)
        value_to_send = int(pv_power)
        try:
            response = client.write_register(address=0, value=value_to_send, slave=1)
            if response.isError():
                print("Modbus write error")
            else:
                print(f"Successfully sent value {value_to_send} to register 0")
        except ModbusException as e:
            print(f"Modbus exception: {e}")
        
        # Wait for next time step (e.g., 60 seconds)
        time.sleep(60)

except KeyboardInterrupt:
    print("Stopping...")
finally:
    client.close()
    print("Connection closed")
